spring.application.name=bd
spring.datasource.url=jdbc:postgresql://localhost:5432/produtosbd
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jba.hibernate.ddl-auto=update


